import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";


export default function Home() {

  const router = useRouter();

  const placeOrderHandler = () => {
    console.log("Placed");
    router.push('/posts')
  }

  return (
    <>
      <Head>
        <title>Page Router Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Page Router</h1>
        <Link href='/users'><h2>Users</h2></Link>
        <Link href='/posts'><h2>Posts</h2></Link>
        <Link href='/todos'><h2>Todos</h2></Link>
        <button onClick={placeOrderHandler}>Place Order</button>
      </main>
    </>
  );
}
